In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
owners =  pd.read_csv('owners revised.csv')
print owners.shape

(1307, 7)


In [3]:
owners.head()

owner  assets_ty  r_d_ty  patents_count  icls_count  industries_count  \
0   13332     18.762   2.503              1           1                 1   
1   13200    865.540  29.965              5           2                 1   
2   23810    248.055  18.696              8           5                 2   
3   62382     54.736  26.312              5           2                 2   
4  125595    278.941  12.971              5           1                 1   

   rnd/patent  
0        2.50  
1        5.99  
2        2.34  
3        5.26  
4        2.59

In [4]:
print ("type of owner column:{}".format(owners['owner'].dtype))
print ("type of assets_ty column:{}".format(owners['assets_ty'].dtype))
print ("type of r_d_ty column:{}".format(owners['r_d_ty'].dtype))
print ("type of patents_count column:{}".format(owners['patents_count'].dtype))
print ("type of icls_count column:{}".format(owners['icls_count'].dtype))
print ("type of industries_count column:{}".format(owners['industries_count'].dtype))
print ("type of rnd/patent column:{}".format(owners['rnd/patent'].dtype))

type of owner column:int64
type of assets_ty column:float64
type of r_d_ty column:float64
type of patents_count column:int64
type of icls_count column:int64
type of industries_count column:int64
type of rnd/patent column:float64


In [5]:
print ("Existing type of owner column:{}".format(owners['owner'].dtype))
owners['owner'] = owners['owner'].astype(object)
print ("Corrected type of owner column:{}".format(owners['owner'].dtype))

Existing type of owner column:int64
Corrected type of owner column:object


In [6]:
owners.describe()

assets_ty        r_d_ty  patents_count   icls_count  \
count    1307.000000   1307.000000    1307.000000  1307.000000   
mean     5416.045796    199.160406      31.413925     6.923489   
std     28013.122523    769.707103     144.992583    14.844842   
min         0.001000      0.000000       1.000000     1.000000   
25%        63.418000      5.840500       1.000000     1.000000   
50%       328.706000     21.476000       4.000000     2.000000   
75%      1900.701000     75.015000      13.000000     6.000000   
max    647483.000000  12183.000000    3250.000000   168.000000   

       industries_count   rnd/patent  
count       1307.000000  1307.000000  
mean           2.155318    23.809855  
std            1.538548   195.611002  
min            1.000000     0.000000  
25%            1.000000     1.580000  
50%            2.000000     3.800000  
75%            3.000000    10.930000  
max            8.000000  6455.000000

In [7]:
print owners.columns.values

['owner' 'assets_ty' 'r_d_ty' 'patents_count' 'icls_count'
 'industries_count' 'rnd/patent']


In [8]:
X_columns = ['assets_ty' ,'r_d_ty' ,'patents_count' ,'icls_count','industries_count', 'rnd/patent']
X = pd.DataFrame(owners, columns= X_columns)
print X.head()

   assets_ty  r_d_ty  patents_count  icls_count  industries_count  rnd/patent
0     18.762   2.503              1           1                 1        2.50
1    865.540  29.965              5           2                 1        5.99
2    248.055  18.696              8           5                 2        2.34
3     54.736  26.312              5           2                 2        5.26
4    278.941  12.971              5           1                 1        2.59


# pre processing

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_std_scaled = scaler.fit(X).transform(X)
#X_scaled = scaler.fit_transform(X)
print X_std_scaled.shape
print X_std_scaled

(1307L, 6L)
[[-0.19274359 -0.25559421 -0.20984223 -0.39917948 -0.75120176 -0.10898166]
 [-0.16250411 -0.21990205 -0.18224405 -0.33179023 -0.75120176 -0.0911333 ]
 [-0.18455526 -0.23454829 -0.16154542 -0.12962248 -0.10098938 -0.10979992]
 ..., 
 [-0.1057161  -0.24715011 -0.16844496 -0.06223323  1.19943539 -0.11516977]
 [-0.18257564 -0.20176874 -0.20984223 -0.39917948 -0.75120176  0.10284617]
 [-0.19228902 -0.25330545 -0.20984223 -0.39917948 -0.75120176 -0.09998077]]


In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler2 = MinMaxScaler()
X_minmax_scaled = scaler2.fit(X).transform(X)
print X_minmax_scaled.shape
print X_minmax_scaled

(1307L, 6L)
[[  2.89752782e-05   2.05450218e-04   0.00000000e+00   0.00000000e+00
    0.00000000e+00   3.87296669e-04]
 [  1.33677487e-03   2.45957482e-03   1.23114805e-03   5.98802395e-03
    0.00000000e+00   9.27962820e-04]
 [  3.83105040e-04   1.53459739e-03   2.15450908e-03   2.39520958e-02
    1.42857143e-01   3.62509682e-04]
 ..., 
 [  3.79274823e-03   7.38734302e-04   1.84672207e-03   2.99401198e-02
    4.28571429e-01   1.99845081e-04]
 [  4.68719643e-04   3.60477715e-03   0.00000000e+00   0.00000000e+00
    0.00000000e+00   6.80402789e-03]
 [  4.86344816e-05   3.49995896e-04   0.00000000e+00   0.00000000e+00
    0.00000000e+00   6.59953524e-04]]


# DBSCAN

In [11]:
from sklearn.cluster import DBSCAN
dbscan = DBSCAN( min_samples=3, eps=0.6)
dbscan_clusters = dbscan.fit_predict(X_std_scaled)
print dbscan_clusters
print dbscan_clusters.shape

unique, counts = np.unique(dbscan_clusters, return_counts=True)
print np.asarray((unique, counts)).T

[0 0 1 ..., 5 0 0]
(1307L,)
[[ -1 112]
 [  0 592]
 [  1 344]
 [  2  41]
 [  3 128]
 [  4  23]
 [  5  64]
 [  6   3]]


In [12]:
dbscan_array = dbscan_clusters
import numpy as np
dbscan_df = pd.concat([owners,pd.DataFrame(dbscan_array, dtype=np.int)], axis=1, ignore_index=True)
dbscan_df.columns = ['owner','assets_ty','r_d_ty','patents_count','icls_count', 'industries_count','rnd/patent','assigned_clusters'] 

In [13]:
metric = [ "assets_ty", "r_d_ty","patents_count","icls_count","industries_count","rnd/patent","assigned_clusters"]
dbscan_df = dbscan_df.drop('owner',axis =1)
d1 = dbscan_df[dbscan_df['assigned_clusters'] == -1].mean()
d2 = dbscan_df[dbscan_df['assigned_clusters'] == 0].mean()
d3 = dbscan_df[dbscan_df['assigned_clusters'] == 1].mean()
d4 = dbscan_df[dbscan_df['assigned_clusters'] == 2].mean()
d5 = dbscan_df[dbscan_df['assigned_clusters'] == 3].mean()
d6 = dbscan_df[dbscan_df['assigned_clusters'] == 4].mean()
d7 = dbscan_df[dbscan_df['assigned_clusters'] == 5].mean()
d8 = dbscan_df[dbscan_df['assigned_clusters'] == 6].mean()

fmt = '{:<5}{:<22}{:<18}{:<18}{:<18}{:<18}{:<18}{:<18}{:<18}{}'

print(fmt.format('', 'samples in cluster', len(dbscan_df[dbscan_df['assigned_clusters'] == -1]),len(dbscan_df[dbscan_df['assigned_clusters'] == 0]),
                                           len(dbscan_df[dbscan_df['assigned_clusters'] == 1]),len(dbscan_df[dbscan_df['assigned_clusters'] == 2]),
                                           len(dbscan_df[dbscan_df['assigned_clusters'] == 3]),len(dbscan_df[dbscan_df['assigned_clusters'] == 4]),
                                           len(dbscan_df[dbscan_df['assigned_clusters'] == 5]),len(dbscan_df[dbscan_df['assigned_clusters'] == 6])))

print(fmt.format('', 'metric', 'd1','d2','d3','d4', 'd5','d6','d7','d8'))
for i, (j,k,l,m,n,o,p,q,r) in enumerate(zip(metric,d1,d2,d3,d4,d5,d6,d7,d8)):
    print(fmt.format(i,j,k,l,m,n,o,p,q,r))

     samples in cluster    112               592               344               41                128               23                64                3
     metric                d1                d2                d3                d4                d5                d6                d7                d8
0    assets_ty             49750.0598036     655.835099662     1175.9049186      4852.88629268     1716.90684375     5550.53256522     2359.07060937     5541.43466667
1    r_d_ty                1793.71599107     26.4964206081     58.3211569767     148.121780488     72.1743359375     124.333956522     76.836734375      189.853666667
2    patents_count         257.544642857     2.29391891892     9.39534883721     52.6585365854     17.2109375        52.6956521739     29.96875          43.6666666667
3    icls_count            37.6785714286     1.33277027027     4.02034883721     16.5365853659     6.0546875         21.3913043478     10.15625          20.6666666667
4    industries_count

In [14]:
dbscan2 = DBSCAN( min_samples=3, eps=0.1)
clusters2 = dbscan2.fit_predict(X_minmax_scaled)
print clusters2
print clusters2.shape

unique, counts = np.unique(clusters2, return_counts=True)
print np.asarray((unique, counts)).T

[0 0 1 ..., 5 0 0]
(1307L,)
[[ -1  40]
 [  0 599]
 [  1 351]
 [  2  51]
 [  3 138]
 [  4  37]
 [  5  71]
 [  6   8]
 [  7   4]
 [  8   5]
 [  9   3]]


# KMeans

In [15]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 4)
kmeans.fit(X_minmax_scaled)
print kmeans.labels_
unique, counts = np.unique(kmeans.labels_, return_counts=True)
print np.asarray((unique,counts)).T

[2 2 0 ..., 1 2 2]
[[  0 501]
 [  1 169]
 [  2 600]
 [  3  37]]


In [16]:
array = kmeans.labels_
import numpy as np
new_dataframe = pd.concat([owners,pd.DataFrame(array, dtype=np.int)], axis=1, ignore_index=True)

In [17]:
print new_dataframe.head()

new_dataframe.columns = ['owner','assets_ty','r_d_ty','patents_count','icls_count', 'industries_count','rnd/patent','assigned_clusters'] 
print new_dataframe.head()
new_dataframe.to_csv('out.csv')

        0        1       2  3  4  5     6  7
0   13332   18.762   2.503  1  1  1  2.50  2
1   13200  865.540  29.965  5  2  1  5.99  2
2   23810  248.055  18.696  8  5  2  2.34  0
3   62382   54.736  26.312  5  2  2  5.26  0
4  125595  278.941  12.971  5  1  1  2.59  2
    owner  assets_ty  r_d_ty  patents_count  icls_count  industries_count  \
0   13332     18.762   2.503              1           1                 1   
1   13200    865.540  29.965              5           2                 1   
2   23810    248.055  18.696              8           5                 2   
3   62382     54.736  26.312              5           2                 2   
4  125595    278.941  12.971              5           1                 1   

   rnd/patent  assigned_clusters  
0        2.50                  2  
1        5.99                  2  
2        2.34                  0  
3        5.26                  0  
4        2.59                  2  


In [18]:
print new_dataframe[new_dataframe['assigned_clusters'] == 0].describe()
print '---------------------------------------------------------------'
print new_dataframe[new_dataframe['assigned_clusters'] == 1].describe()
print '---------------------------------------------------------------'
print new_dataframe[new_dataframe['assigned_clusters'] == 2].describe()
print '---------------------------------------------------------------'
print new_dataframe[new_dataframe['assigned_clusters'] == 3].describe()

           assets_ty       r_d_ty  patents_count  icls_count  \
count     501.000000   501.000000     501.000000  501.000000   
mean     3419.044391   163.628503      14.988024    5.000000   
std     12590.980122   533.074406      31.897709    4.145841   
min         1.695000     0.074000       2.000000    2.000000   
25%       118.850000    10.638000       4.000000    2.000000   
50%       438.900000    27.684000       6.000000    4.000000   
75%      1779.092000    88.800000      13.000000    6.000000   
max    174278.000000  4947.000000     438.000000   35.000000   

       industries_count   rnd/patent  assigned_clusters  
count        501.000000   501.000000              501.0  
mean           2.291417    18.584910                0.0  
std            0.454869    82.825676                0.0  
min            2.000000     0.020000                0.0  
25%            2.000000     1.730000                0.0  
50%            2.000000     3.610000                0.0  
75%            3.

In [19]:
metric = [ "assets_ty", "r_d_ty","patents_count","icls_count","industries_count","rnd/patent","assigned_clusters"]
new_dataframe = new_dataframe.drop('owner',axis =1)
a = new_dataframe[new_dataframe['assigned_clusters'] == 0].mean()
b = new_dataframe[new_dataframe['assigned_clusters'] == 1].mean()
c = new_dataframe[new_dataframe['assigned_clusters'] == 2].mean()
d = new_dataframe[new_dataframe['assigned_clusters'] == 3].mean()

fmt = '{:<5}{:<25}{:<25}{:<25}{:<25}{}'

print(fmt.format('', 'samples in cluster', len(new_dataframe[new_dataframe['assigned_clusters'] == 0]),
                 len(new_dataframe[new_dataframe['assigned_clusters'] == 1]),
                 len(new_dataframe[new_dataframe['assigned_clusters'] == 2]),
                 len(new_dataframe[new_dataframe['assigned_clusters'] == 3])))

print(fmt.format('', 'metric', 'a','b','c','d'))
for i, (j,p,q,r,s) in enumerate(zip(metric,a,b,c,d)):
    print(fmt.format(i,j,p,q,r,s))

     samples in cluster       501                      169                      600                      37
     metric                   a                        b                        c                        d
0    assets_ty                3419.04439122            9515.54981065            1524.98940667            76829.9744054
1    r_d_ty                   163.628502994            360.514532544            44.4202833333            2452.585
2    patents_count            14.9880239521            64.6804733728            2.28166666667            574.297297297
3    icls_count               5.0                      17.3846153846            1.33333333333            75.8378378378
4    industries_count         2.29141716567            4.83431952663            1.0                      6.81081081081
5    rnd/patent               18.5849101796            7.9175147929             33.6030833333            8.33864864865
6    assigned_clusters        0.0                      1.0                  

# Dendrogram

In [20]:
from scipy.cluster.hierarchy import dendrogram,ward
linkage_array = ward(X_minmax_scaled)
dendrogram(linkage_array)
ax= plt.gca()
bounds = ax.get_xbound()
ax.plot(bounds,[7,7],'--',c='k')
ax
plt.xlabel("sample index")

In [21]:
plt.show()

# KMeans at 3 asset levels

In [61]:
print("All owners: {}".format( X.shape))

till_1k = pd.read_csv('owners revised - till1k.csv')
from1to10k = pd.read_csv('owners revised - 1kto10k.csv')
above_10k = pd.read_csv('owners revised - above10k.csv')

X_columns = ['assets_ty' ,'r_d_ty' ,'patents_count' ,'icls_count','industries_count', 'rnd/patent']
X_till_1k = pd.DataFrame(till_1k, columns= X_columns)
X_1k_10k = pd.DataFrame(from1to10k, columns= X_columns)
X_above_10k = pd.DataFrame(above_10k, columns= X_columns)

print("owners with assets_ty less than 1k: {}".format( X_till_1k.shape))
print("owners with assets_ty between 1k and 10k : {}".format( X_1k_10k.shape))
print("owners with assets_ty above 10k: {}".format( X_above_10k.shape))
print "-----------"
print type(X_till_1k)
print X_1k_10k['assets_ty'].min()
print X_1k_10k['assets_ty'].max()
print "-----------"
#rint X_1k_10k['assets_ty']


All owners: (1307, 6)
owners with assets_ty less than 1k: (884, 6)
owners with assets_ty between 1k and 10k : (309, 6)
owners with assets_ty above 10k: (114, 6)
-----------
<class 'pandas.core.frame.DataFrame'>
1000.953
9955.0
-----------


In [62]:
from sklearn.preprocessing import MinMaxScaler
scaler1 = MinMaxScaler()
scaler2 = MinMaxScaler()
scaler3 = MinMaxScaler()

X_till_1k_scaled = scaler1.fit(X_till_1k).transform(X_till_1k)
X_1k_10k_scaled = scaler2.fit(X_1k_10k).transform(X_1k_10k)
X_above_10k_scaled = scaler3.fit(X_above_10k).transform(X_above_10k)

print X_till_1k_scaled.shape
print X_1k_10k_scaled.shape
print X_above_10k_scaled.shape


(884L, 6L)
(309L, 6L)
(114L, 6L)


In [63]:
from sklearn.cluster import KMeans
kmeans_till_1k = KMeans(n_clusters = 4)
kmeans_1k_10k = KMeans(n_clusters = 4)
kmeans_above_10k = KMeans(n_clusters = 4)

kmeans_till_1k = kmeans_till_1k.fit(X_till_1k_scaled)
kmeans_1k_10k = kmeans_1k_10k.fit(X_1k_10k_scaled)
kmeans_above_10k = kmeans_above_10k.fit(X_above_10k_scaled)

unique1, counts1 = np.unique(kmeans_till_1k.labels_, return_counts=True)
print np.asarray((unique1,counts1)).T

unique2, counts2 = np.unique(kmeans_1k_10k.labels_, return_counts=True)
print np.asarray((unique2,counts2)).T

unique3, counts3 = np.unique(kmeans_above_10k.labels_, return_counts=True)
print np.asarray((unique3,counts3)).T

[[  0 161]
 [  1 404]
 [  2 100]
 [  3 219]]
[[  0 124]
 [  1  51]
 [  2  94]
 [  3  40]]
[[ 0 48]
 [ 1 54]
 [ 2  5]
 [ 3  7]]


In [64]:
array_till_1k = kmeans_till_1k.labels_
array_1k_10k = kmeans_1k_10k.labels_
array_above_10k = kmeans_above_10k.labels_

import numpy as np

df_till_1k = pd.concat([till_1k,pd.DataFrame(array_till_1k, dtype=np.int)], axis=1, ignore_index=True)
df_1k_10k = pd.concat([from1to10k,pd.DataFrame(array_1k_10k, dtype=np.int)], axis=1, ignore_index=True)
df_above_10k = pd.concat([above_10k,pd.DataFrame(array_above_10k, dtype=np.int)], axis=1, ignore_index=True)

df_till_1k.columns = ['owner','assets_ty','r_d_ty','patents_count','icls_count','industries_count','rnd/patent','assigned_clusters'] 
df_1k_10k.columns = ['owner','assets_ty','r_d_ty','patents_count','icls_count','industries_count','rnd/patent','assigned_clusters'] 
df_above_10k.columns = ['owner','assets_ty','r_d_ty','patents_count','icls_count','industries_count','rnd/patent','assigned_clusters'] 

df_till_1k.to_csv('df_till_1k.csv')
df_1k_10k.to_csv('df_1k_10k.csv')
df_above_10k.to_csv('df_above_10k.csv')


## clusters of owners with assets less than 1k

In [65]:
metric = [ "assets_ty", "r_d_ty","patents_count","icls_count","industries_count","rnd/patent","assigned_clusters"]
df_till_1k = df_till_1k.drop('owner',axis =1)

a1 = df_till_1k[df_till_1k['assigned_clusters'] == 0].mean()
b1 = df_till_1k[df_till_1k['assigned_clusters'] == 1].mean()
c1 = df_till_1k[df_till_1k['assigned_clusters'] == 2].mean()
d1 = df_till_1k[df_till_1k['assigned_clusters'] == 3].mean()

fmt = '{:<5}{:<25}{:<25}{:<25}{:<25}{}'

print(fmt.format('', 'samples in cluster', len(df_till_1k[df_till_1k['assigned_clusters'] == 0]),
                 len(df_till_1k[df_till_1k['assigned_clusters'] == 1]),
                 len(df_till_1k[df_till_1k['assigned_clusters'] == 2]),
                 len(df_till_1k[df_till_1k['assigned_clusters'] == 3])))

print(fmt.format('','metric', 'a1','b1','c1','d1'))
for i, (j,p,q,r,s) in enumerate(zip(metric,a1,b1,c1,d1)):
    print(fmt.format(i,j,p,q,r,s))
    
    

     samples in cluster       161                      404                      100                      219
     metric                   a1                       b1                       c1                       d1
0    assets_ty                557.122950311            79.4909084158            498.03245                113.231977169
1    r_d_ty                   46.4156024845            8.3965049505             46.11599                 17.624739726
2    patents_count            4.10559006211            1.93811881188            20.81                    5.899543379
3    icls_count               2.26086956522            1.2599009901             7.8                      3.28310502283
4    industries_count         1.4099378882             1.0                      3.35                     2.14611872146
5    rnd/patent               21.0400621118            6.07143564356            3.1275                   3.86707762557
6    assigned_clusters        0.0                      1.0              

## clusters of owners with assets between 1k and 10k

In [66]:
metric = [ "assets_ty", "r_d_ty","patents_count","icls_count","industries_count","rnd/patent","assigned_clusters"]
df_1k_10k = df_1k_10k.drop('owner',axis =1)

a2 = df_1k_10k[df_1k_10k['assigned_clusters'] == 0].mean()
b2 = df_1k_10k[df_1k_10k['assigned_clusters'] == 1].mean()
c2 = df_1k_10k[df_1k_10k['assigned_clusters'] == 2].mean()
d2 = df_1k_10k[df_1k_10k['assigned_clusters'] == 3].mean()

fmt = '{:<5}{:<25}{:<25}{:<25}{:<25}{}'

print(fmt.format('', 'samples in cluster', len(df_1k_10k[df_1k_10k['assigned_clusters'] == 0]),
                 len(df_1k_10k[df_1k_10k['assigned_clusters'] == 1]),
                 len(df_1k_10k[df_1k_10k['assigned_clusters'] == 2]),
                 len(df_1k_10k[df_1k_10k['assigned_clusters'] == 3])))

print(fmt.format('', 'metric', 'a2','b2','c2','d2'))
for i, (j,p,q,r,s) in enumerate(zip(metric,a2,b2,c2,d2)):
    print(fmt.format(i,j,p,q,r,s))

     samples in cluster       124                      51                       94                       40
     metric                   a2                       b2                       c2                       d2
0    assets_ty                2047.1573871             6833.33462745            2392.58351064            6738.6798
1    r_d_ty                   103.43983871             201.546078431            120.004287234            313.4687
2    patents_count            10.4112903226            15.3137254902            45.5319148936            164.575
3    icls_count               3.58870967742            4.70588235294            12.2127659574            28.4
4    industries_count         1.45967741935            2.01960784314            3.8829787234             5.625
5    rnd/patent               31.2383064516            51.6582352941            4.38957446809            3.6685
6    assigned_clusters        0.0                      1.0                      2.0                      3.0


## clusters of owners with assets above 10k

In [67]:
metric = [ "assets_ty", "r_d_ty","patents_count","icls_count","industries_count","rnd/patent","assigned_clusters"]
df_above_10k = df_above_10k.drop('owner',axis =1)

a3 = df_above_10k[df_above_10k['assigned_clusters'] == 0].mean()
b3 = df_above_10k[df_above_10k['assigned_clusters'] == 1].mean()
c3 = df_above_10k[df_above_10k['assigned_clusters'] == 2].mean()
d3 = df_above_10k[df_above_10k['assigned_clusters'] == 3].mean()

fmt = '{:<5}{:<25}{:<25}{:<25}{:<25}{}'

print(fmt.format('', 'samples in cluster', len(df_above_10k[df_above_10k['assigned_clusters'] == 0]),
                 len(df_above_10k[df_above_10k['assigned_clusters'] == 1]),
                 len(df_above_10k[df_above_10k['assigned_clusters'] == 2]),
                 len(df_above_10k[df_above_10k['assigned_clusters'] == 3])))

print(fmt.format('', 'metric', 'a3','b3','c3','d3'))
for i, (j,p,q,r,s) in enumerate(zip(metric,a3,b3,c3,d3)):
    print(fmt.format(i,j,p,q,r,s))

     samples in cluster       48                       54                       5                        7
     metric                   a3                       b3                       c3                       d3
0    assets_ty                28963.1300833            40123.9776296            180627.0                 189357.432143
1    r_d_ty                   961.663833333            1486.07194444            3189.8                   7383.54914286
2    patents_count            232.770833333            33.1666666667            1633.4                   310.714285714
3    icls_count               46.5                     7.42592592593            140.4                    53.2857142857
4    industries_count         6.16666666667            2.44444444444            7.8                      5.71428571429
5    rnd/patent               7.65416666667            304.433148148            1.964                    33.6342857143
6    assigned_clusters        0.0                      1.0             